#!/bin/sh

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## Configuration
logo=$DIR/assets/logo.png

hmargin=3cm
vmargin=3.5cm

rm $2

java -jar $DIR/bin/plantuml.jar -o output $1

pandoc -t json $1 | $DIR/bin/parse_plantuml $1 | pandoc -f json -N -V fontsize=12pt -V logo=$logo --template=$DIR/mytemplate.tex --latex-engine=xelatex --highlight-style pygments --toc -o $2

rm -rf output

open $2