#!/bin/sh

## Configuration
logo=assets/logo.png

hmargin=3cm
vmargin=3.5cm

rm README.pdf
rm output/*.png

java -jar bin/plantuml.jar -o output README.md

pandoc -t json README.md | bin/parse_plantuml | pandoc -f json -N -V fontsize=12pt -V logo=$logo --template=mytemplate.tex --latex-engine=xelatex --highlight-style pygments --toc -o README.pdf

open README.pdf